[package]
name = "escrow-x-sc-freelancer-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.escrow-x-sc-freelancer]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.56.1"
default-features = false
